### ISSUE TITLE
Update option in excel is not working for entities

### ISSUE THREAD

**Issue by madhuchandah** [acquia-pso/dst-entity-generate#153]
**Steps:**
- Navigate to sheet
- Update any of the field/fields for Bundles or User Menus or Menus
- Set Implementation status as ‘c’(update)
- Clear cache
- Execute command

**Issue:**
- Fields updated in excel sheet are not updated in Drupal BE

**Comment by omkar-pednekar** [comment]
Hi @madhuchandah ,

Could you please validate this issue. If not valid, please close it.

**Comment by omkar-pednekar** [comment]
Closing issue as update mode is working as expected.
