### ISSUE TITLE
Found potential security vulnerabilities in the composer dependencies

### ISSUE THREAD

**Issue by vyasamit2007** [acquia-pso/dst-entity-generate#154]
**Description of the bug**
[The Dependabot](https://github.com/acquia-pso/dst-entity-generate/security/dependabot) found potential security vulnerabilities in the dependencies of the repository.

**How to reproduce the bug?**
Go to security and find the list, added a screenshot of the list if there is an issue with the access.

**Screenshots**
![image](https://user-images.githubusercontent.com/1127619/119626445-d8c9b880-be28-11eb-9964-ce3de3d0994f.png)

**Comment by omkar-pednekar** [comment]
Hi @vyasamit2007 ,

I have updated packages. Could you please check it once whether it have solved security vulnerabilities issue.
