### ISSUE TITLE
Content type with empty name and description can be created in backend , validation not applied for Name & Description fields

### ISSUE THREAD

**Issue by madhuchandah** [acquia-pso/dst-entity-generate#158]
**Steps:**
- Navigate to DST sheet
- Enter machine name and select entity type as Content type
- Keep Name and Description as an empty
- Clear cache
- Run command

**Issue:**
- Content type with empty name and description is created in backend

**Expected:**
- While generating entity at least Name should be mandatory field

**Screenshots**
<img width="1666" alt="Screenshot 2021-05-27 at 11 26 27 AM" src="https://user-images.githubusercontent.com/44256250/119775450-3d484e80-bee1-11eb-8caa-b7cd1c061ee0.png">
<img width="1660" alt="Screenshot 2021-05-27 at 11 26 36 AM" src="https://user-images.githubusercontent.com/44256250/119775456-3f121200-bee1-11eb-99bc-13dd8c39d3f6.png">

**Comment by omkar-pednekar** [comment]
Closing issue as it is fixed.
