### ISSUE TITLE
Getting error to configure private file path when trying to configure DEG tool

### ISSUE THREAD

**Issue by vibhutisuneja005** [acquia-pso/dst-entity-generate#172]
**Description of the bug**
Getting error to configure private file path when trying to configure DEG tool

**How to reproduce the bug?**
Steps to reproduce the behaviour:
1) Install DEG from Drupal BE http://127.0.0.1:1234/admin/config/dst_entity_generate/settings/google_sheet_api
2) Click on configure tab & notice that it should navigate to the Google Sheet API page in Drupal BE

**Expected behavior**

**Actual behavior**
Getting "Please configure private file path." error on Google Sheet APi page in Drupal BE

**Screenshots**
![image](https://user-images.githubusercontent.com/42436653/120626022-e235cf00-c47f-11eb-8029-488e6f0ed192.png)

@omkar-pednekar Kindly have a look

**Comment by omkar-pednekar** [comment]
Error message changed and documentation updated.

**Comment by sharique** [comment]
This is not related to DST,  the site is not configured properly.
