### ISSUE TITLE
Getting wrong moderation values which are set at the time of saving the content

### ISSUE THREAD

**Issue by vibhutisuneja005** [acquia-pso/dst-entity-generate#173]
**Description of the bug**
Getting wrong moderation values which are set at the time of saving the content

**How to reproduce the bug?**
1) Create content type & fields using DEG sheet ( ex-  Article)
2) Generate work flow, states using DEG sheet
3) Create article content & change it's work flow state to different states ( ex- published to draft or unpublished to published)
4) Now go to /admin/content page and check the status of content & notice the the moderation value is not the same that we saved.

**Expected behaviour**
It should show the same moderation value that we save at the time of content creation

**Actual behaviour**
Getting wrong moderation values which are set at the time of saving the content

**Screenshots**
![image](https://user-images.githubusercontent.com/42436653/120632571-bb2ecb80-c486-11eb-9f55-605bf342b5ab.png)
![image](https://user-images.githubusercontent.com/42436653/120632596-c1bd4300-c486-11eb-8809-abc31372dc77.png)

**Additional context**
@omkar-pednekar Kindly have a look

**Comment by omkar-pednekar** [comment]
This is fixed.
