### ISSUE TITLE
Content is not visible to the anonymous user when the moderation state is published

### ISSUE THREAD

**Issue by vibhutisuneja005** [acquia-pso/dst-entity-generate#174]
**Description of the bug**
Content is not visible to the anonymous user when the moderation state is published

**How to reproduce the bug?**
1) Create content type & fields using DEG sheet ( ex- Article)
2) Generate work flow, states using DEG sheet
3) Create article content & change it's work flow state to Published
4) Access content as anonymous user

**Expected behavior**
User should be able to access the page as the work flow status is published

**Actual behavior**
Content is not visible to the anonymous user when the moderation state is published

**Screenshots**

**Additional context**
@omkar-pednekar Kindly have a look

**Comment by omkar-pednekar** [comment]
This is fixed with https://github.com/acquia-pso/dst-entity-generate/issues/173 issue.
